### ISSUE TITLE
linear id [(1,1)] is NaN

### ISSUE THREAD

**Issue by Bodigrim** [phadej/regression-simple#10]
```
> linear id [(1,1)]
V2 NaN NaN
> linear id [(1,1), (1,1)]
V2 NaN NaN
> linear id [(1,1), (1,2)]
V2 NaN NaN
```
I'd expect all cases to return non-NaN values: the first two should be `V2 1 0` and the third one should be `V2 1.5 0`.

**Comment by phadej** [comment]
That would be arbitrary.

Current behaviour is garbage in garbage out.

OpenOffice Calc doesn't seem to do any special casing

![Screenshot from 2023-04-05 09-01-33](https://user-images.githubusercontent.com/51087/229994173-ff7ddc8b-ff96-41c2-9329-3ba8a1ab337d.png)

nor `gnuplot`

```
iter      chisq       delta/lim  lambda   alpha         beta         
   0 1.0000000000e+00   0.00e+00  1.00e+00    1.000000e+00   1.000000e+00
   1 5.2000000000e-01  -9.23e+04  1.00e-01    8.000000e-01   8.000000e-01
   2 5.0000012438e-01  -4.00e+03  1.00e-02    7.501247e-01   7.501247e-01
   3 5.0000000000e-01  -2.49e-02  1.00e-03    7.500000e-01   7.500000e-01
         "linear.gnu", line 3: Singular matrix in Invert_RtR
```

I don't know why `regression-simple` should either.

**Comment by Bodigrim** [comment]
Thanks, makes sense. Dunno, maybe worth to add a comment.
